# Included by every frontend script
# RETROCORE variable must be set


ADDON="plugin.program.retroarch"
ADDONDIR="$HOME/.xbmc/addons/$ADDON"
RETROARCH="$ADDONDIR/libexec/retroarch"
CONFDIR="$HOME/.xbmc/userdata/addon_data/$ADDON"
COREDIR="$HOME/.xbmc/addons/$ADDON/lib"
EMUDIR="$HOME/emulators/retroarch"
RETROCORE="$1"; shift

CONFFILE="$CONFDIR/${RETROCORE}_retroarch.cfg"
if [ "$RETROCORE" = "menu" ] || [ -z "$RETROCORE" ]; then
  RETROCORE="menu"
  COREFILE=""
else
  COREFILE="$COREDIR/${RETROCORE}_libretro.so"
fi

# Stop and restart xbmc automatically
systemctl stop xbmc
sleep 0.2

trap 'systemctl start xbmc' EXIT

# Switch to 60 Hz
xrandr -r 60

# Compute ALSA device
AUDIODEV="$(grep audiodevice $HOME/.xbmc/userdata/guisettings.xml | sed 's/.*ALSA:\(.*\)<\/audiodevice.*/\1/')"

# Create directory structure in emulators

for d in roms states saves screenshots overlays input; do
  [ -d "$EMUDIR/$d" ] || mkdir -p "$EMUDIR/$d"
done

# Create configuration if necessary
mkdir -p "$CONFDIR"
if ! [ -e "$CONFFILE" ]; then
  # Generate new configuration for this core
  cat > "$CONFFILE" <<EOF
config_save_on_exit = "true"
input_axis_threshold = "0.500000"
load_dummy_on_core_shutdown = "true"
fps_show = "false"
rewind_enable = "false"
audio_latency = "32"
audio_sync = "true"
audio_block_frames = "0"
rewind_granularity = "1"
video_shader_enable = "false"
video_aspect_ratio = "-1.000000"
video_windowed_fullscreen = "true"
video_scale = "3.000000"
autosave_interval = "0"
video_crop_overscan = "true"
video_scale_integer = "false"
video_smooth = "true"
video_threaded = "false"
video_shared_context = "false"
video_fullscreen = "true"
video_refresh_rate = "60"
video_monitor_index = "0"
video_fullscreen_x = "0"
video_fullscreen_y = "0"
video_driver = "gl"
menu_driver = "rgui"
video_vsync = "true"
video_hard_sync = "false"
video_hard_sync_frames = "0"
video_black_frame_insertion = "false"
video_disable_composition = "false"
pause_nonactive = "false"
video_swap_interval = "1"
video_gpu_screenshot = "true"
video_rotation = "0"
screenshot_directory = "$EMUDIR/screenshots"
aspect_ratio_index = "19"
camera_allow = "false"
audio_rate_control = "true"
audio_rate_control_delta = "0.005000"
audio_driver = "alsa"
audio_enable = "true"
audio_out_rate = "48000"
location_allow = "false"
video_font_size = "32.000000"
video_font_enable = "true"
system_directory = "$EMUDIR/system"
audio_resampler = "sinc"
savefile_directory = "$EMUDIR/saves"
savestate_directory = "$EMUDIR/states"
video_shader_dir = "default"
video_filter_dir = "default"
audio_filter_dir = "default"
content_directory = "$EMUDIR/roms"
assets_directory = "default"
rgui_browser_directory = "$EMUDIR/roms"
rgui_config_directory = "default"
rgui_show_start_screen = "false"
game_history_path = "$EMUDIR/history.txt"
game_history_size = "100"
input_autodetect_enable = "true"
overlay_directory = "$EMUDIR/overlays/"
input_overlay_opacity = "0.700000"
input_overlay_scale = "1.000000"
gamma_correction = "false"
triple_buffering_enable = "false"
soft_filter_enable = "false"
flicker_filter_enable = "false"
flicker_filter_index = "0"
soft_filter_index = "0"
current_resolution_id = "0"
custom_viewport_width = "960"
custom_viewport_height = "720"
custom_viewport_x = "0"
custom_viewport_y = "0"
block_sram_overwrite = "false"
savestate_auto_index = "false"
savestate_auto_save = "false"
savestate_auto_load = "true"
fastforward_ratio = "-1.000000"
slowmotion_ratio = "3.000000"
sound_mode = "0"
state_slot = "0"
user_language = "0"
custom_bgm_enable = "false"
input_driver = "udev"
input_device_p1 = "0"
input_player1_joypad_index = "0"
input_libretro_device_p1 = "1"
input_player1_analog_dpad_mode = "0"
input_device_p2 = "0"
input_player2_joypad_index = "1"
input_libretro_device_p2 = "1"
input_player2_analog_dpad_mode = "0"
input_device_p3 = "0"
input_player3_joypad_index = "2"
input_libretro_device_p3 = "1"
input_player3_analog_dpad_mode = "0"
input_device_p4 = "0"
input_player4_joypad_index = "3"
input_libretro_device_p4 = "1"
input_player4_analog_dpad_mode = "0"
input_device_p5 = "0"
input_player5_joypad_index = "4"
input_libretro_device_p5 = "1"
input_player5_analog_dpad_mode = "0"
input_device_p6 = "0"
input_player6_joypad_index = "5"
input_libretro_device_p6 = "1"
input_player6_analog_dpad_mode = "0"
input_device_p7 = "0"
input_player7_joypad_index = "6"
input_libretro_device_p7 = "1"
input_player7_analog_dpad_mode = "0"
input_device_p8 = "0"
input_player8_joypad_index = "7"
input_libretro_device_p8 = "1"
input_player8_analog_dpad_mode = "0"
input_player1_b = "z"
input_player1_b_btn = "0"
input_player1_b_axis = "nul"
input_player1_y = "a"
input_player1_y_btn = "2"
input_player1_y_axis = "nul"
input_player1_select = "rshift"
input_player1_select_btn = "6"
input_player1_select_axis = "nul"
input_player1_start = "enter"
input_player1_start_btn = "7"
input_player1_start_axis = "nul"
input_player1_up = "up"
input_player1_up_btn = "h0up"
input_player1_up_axis = "nul"
input_player1_down = "down"
input_player1_down_btn = "h0down"
input_player1_down_axis = "nul"
input_player1_left = "left"
input_player1_left_btn = "h0left"
input_player1_left_axis = "nul"
input_player1_right = "right"
input_player1_right_btn = "h0right"
input_player1_right_axis = "nul"
input_player1_a = "x"
input_player1_a_btn = "1"
input_player1_a_axis = "nul"
input_player1_x = "s"
input_player1_x_btn = "3"
input_player1_x_axis = "nul"
input_player1_l = "q"
input_player1_l_btn = "4"
input_player1_l_axis = "nul"
input_player1_r = "w"
input_player1_r_btn = "5"
input_player1_r_axis = "nul"
input_player1_l2 = "nul"
input_player1_l2_btn = "nul"
input_player1_l2_axis = "+2"
input_player1_r2 = "nul"
input_player1_r2_btn = "nul"
input_player1_r2_axis = "+5"
input_player1_l3 = "nul"
input_player1_l3_btn = "9"
input_player1_l3_axis = "nul"
input_player1_r3 = "nul"
input_player1_r3_btn = "10"
input_player1_r3_axis = "nul"
input_player1_l_x_plus = "nul"
input_player1_l_x_plus_btn = "nul"
input_player1_l_x_plus_axis = "+0"
input_player1_l_x_minus = "nul"
input_player1_l_x_minus_btn = "nul"
input_player1_l_x_minus_axis = "-0"
input_player1_l_y_plus = "nul"
input_player1_l_y_plus_btn = "nul"
input_player1_l_y_plus_axis = "-1"
input_player1_l_y_minus = "nul"
input_player1_l_y_minus_btn = "nul"
input_player1_l_y_minus_axis = "+1"
input_player1_r_x_plus = "nul"
input_player1_r_x_plus_btn = "nul"
input_player1_r_x_plus_axis = "+3"
input_player1_r_x_minus = "nul"
input_player1_r_x_minus_btn = "nul"
input_player1_r_x_minus_axis = "-3"
input_player1_r_y_plus = "nul"
input_player1_r_y_plus_btn = "nul"
input_player1_r_y_plus_axis = "-4"
input_player1_r_y_minus = "nul"
input_player1_r_y_minus_btn = "nul"
input_player1_r_y_minus_axis = "+4"
input_player1_turbo = "nul"
input_player1_turbo_btn = "nul"
input_player1_turbo_axis = "nul"
input_toggle_fast_forward = "space"
input_toggle_fast_forward_btn = "nul"
input_toggle_fast_forward_axis = "nul"
input_hold_fast_forward = "l"
input_hold_fast_forward_btn = "nul"
input_hold_fast_forward_axis = "nul"
input_load_state = "f4"
input_load_state_btn = "nul"
input_load_state_axis = "nul"
input_save_state = "f2"
input_save_state_btn = "nul"
input_save_state_axis = "nul"
input_toggle_fullscreen = "f"
input_toggle_fullscreen_btn = "nul"
input_toggle_fullscreen_axis = "nul"
input_exit_emulator = "escape"
input_exit_emulator_btn = "nul"
input_exit_emulator_axis = "nul"
input_state_slot_increase = "f7"
input_state_slot_increase_btn = "nul"
input_state_slot_increase_axis = "nul"
input_state_slot_decrease = "f6"
input_state_slot_decrease_btn = "nul"
input_state_slot_decrease_axis = "nul"
input_rewind = "r"
input_rewind_btn = "nul"
input_rewind_axis = "nul"
input_movie_record_toggle = "o"
input_movie_record_toggle_btn = "nul"
input_movie_record_toggle_axis = "nul"
input_pause_toggle = "p"
input_pause_toggle_btn = "nul"
input_pause_toggle_axis = "nul"
input_frame_advance = "k"
input_frame_advance_btn = "nul"
input_frame_advance_axis = "nul"
input_reset = "h"
input_reset_btn = "nul"
input_reset_axis = "nul"
input_shader_next = "m"
input_shader_next_btn = "nul"
input_shader_next_axis = "nul"
input_shader_prev = "n"
input_shader_prev_btn = "nul"
input_shader_prev_axis = "nul"
input_cheat_index_plus = "y"
input_cheat_index_plus_btn = "nul"
input_cheat_index_plus_axis = "nul"
input_cheat_index_minus = "t"
input_cheat_index_minus_btn = "nul"
input_cheat_index_minus_axis = "nul"
input_cheat_toggle = "u"
input_cheat_toggle_btn = "nul"
input_cheat_toggle_axis = "nul"
input_screenshot = "f8"
input_screenshot_btn = "nul"
input_screenshot_axis = "nul"
input_audio_mute = "f9"
input_audio_mute_btn = "nul"
input_audio_mute_axis = "nul"
input_netplay_flip_players = "i"
input_netplay_flip_players_btn = "nul"
input_netplay_flip_players_axis = "nul"
input_slowmotion = "e"
input_slowmotion_btn = "nul"
input_slowmotion_axis = "nul"
input_enable_hotkey = "nul"
input_enable_hotkey_btn = "nul"
input_enable_hotkey_axis = "nul"
input_volume_up = "add"
input_volume_up_btn = "nul"
input_volume_up_axis = "nul"
input_volume_down = "subtract"
input_volume_down_btn = "nul"
input_volume_down_axis = "nul"
input_overlay_next = "nul"
input_overlay_next_btn = "nul"
input_overlay_next_axis = "nul"
input_disk_eject_toggle = "nul"
input_disk_eject_toggle_btn = "nul"
input_disk_eject_toggle_axis = "nul"
input_disk_next = "nul"
input_disk_next_btn = "nul"
input_disk_next_axis = "nul"
input_grab_mouse_toggle = "f11"
input_grab_mouse_toggle_btn = "nul"
input_grab_mouse_toggle_axis = "nul"
input_menu_toggle = "f1"
input_menu_toggle_btn = "8"
input_menu_toggle_axis = "nul"
core_specific_config = "false"
libretro_log_level = "0"
log_verbosity = "false"
perfcnt_enable = "false"
libretro_path = "$COREFILE"
audio_device = "$AUDIODEV"
libretro_directory = "$COREDIR"
libretro_info_path = ""
cheat_database_path = ""
video_shader = ""
video_filter = ""
audio_dsp_plugin = ""
camera_device = ""
extraction_directory = ""
joypad_autoconfig_dir = "$EMUDIR/input"
input_overlay = ""
netplay_nickname = ""
input_joypad_driver = ""
input_keyboard_layout = ""
EOF
fi

# Ready to go !
chmod +x "$RETROARCH"
if [ "$1" ]; then
  "$RETROARCH" -c "$CONFFILE" "$@"
else
  "$RETROARCH" -c "$CONFFILE" --menu
fi
